POST http://localhost:7071/api/users
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Passw0rd123"
}

###

# @name login
POST http://localhost:7071/api/users/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Passw0rd123"
}

###

@accessToken = {{login.response.body.$.result.authorization.accessToken.token}}

POST http://localhost:7071/api/stores
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Example Store 3"
}

###

# Update Store (JSON)
PUT http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "country": "US",
  "currency": "USD",
  "status": "active"
}

###

# Get Stores
GET http://localhost:7071/api/stores
Authorization: Bearer {{accessToken}}

###

# Update Store (Form Data)
PUT http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="name"

Example Store 1

------boundary
Content-Disposition: form-data; name="logo"; filename="chicken-shapes-0.webp"
Content-Type: image/webp

< /Users/jacob/Desktop/chicken-shapes-0.webp
------boundary--

###

# Get Products
GET http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/products
Authorization: Bearer {{accessToken}}

###

# Delete Product
DELETE http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/products/87bea2b7-1f6f-4d3f-8d09-e8c493603cf4
Authorization: Bearer {{accessToken}}

###

# Create Product
POST http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Einstein Collection Metal Puzzles",
  "description": "Formed of the symbols of Einstein's ground-breaking E=mc2 equation, see if you can separate the two pieces of each metal puzzle and then reattach them Developed in 1905, Einstein's famous theory...",
  "price": 19.99,
  "imageUrls": [
    "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781683837695/harry-potter-spells-and-charms-ruled-pocket-journal-9781683837695_xlg.jpg"
  ],
  "barcode": {
    "format": "ean_13",
    "code": "5060506531397"
  }
}

###

# Get Product
GET http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/products/0e09d84f-69ef-427b-998e-2cbd1be82dfb
Authorization: Bearer {{accessToken}}

###

# Add Image to Product
POST http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/products/0e09d84f-69ef-427b-998e-2cbd1be82dfb
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="images[]"; filename="daniel-1.png"
Content-Type: image/png

< /Users/jacob/Desktop/30d6c9db80103db06eaf6ca9d8507307-sticker.png
------boundary
Content-Disposition: form-data; name="images[]"; filename="daniel-2.png"
Content-Type: image/png

< /Users/jacob/Desktop/61c301c039bd1c40c53823a5ea7021f5-sticker.png
------boundary--

###

# Checkout
POST http://localhost:7071/api/stores/7bf97742-b545-40d0-a279-33a95129616a/checkout
Content-Type: application/json

{
  "items": [
    {
      "productId": "129f151c-22d3-4427-8754-c79333a0daa1",
      "quantity": 3
    },
    {
      "productId": "1c86d717-7d65-4ce1-9e53-26fffb2e751e",
      "quantity": 2
    },
    {
      "productId": "85ead4cc-500e-480f-b478-f31eee68a254",
      "quantity": 6
    }
  ]
}
